name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image (Optional Push)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: shaundamon/my-django-app:latest
        build-args: |
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=${{ secrets.DEBUG }}
          ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
          EMAIL_BACKEND=${{ secrets.EMAIL_BACKEND }}
          EMAIL_HOST=${{ secrets.EMAIL_HOST }}
          EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}
          EMAIL_PORT=${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}
          AWS_S3_CUSTOM_DOMAIN=${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
          AWS_S3_OBJECT_PARAMETERS=${{ secrets.AWS_S3_OBJECT_PARAMETERS }}
          AWS_LOCATION=${{ secrets.AWS_LOCATION }}
          AWS_DEFAULT_ACL=${{ secrets.AWS_DEFAULT_ACL }}
          AWS_QUERYSTRING_AUTH=${{ secrets.AWS_QUERYSTRING_AUTH }}
          STACKHERO_POSTGRESQL_ADMIN_PASSWORD=${{ secrets.STACKHERO_POSTGRESQL_ADMIN_PASSWORD }}
          STACKHERO_POSTGRESQL_HOST=${{ secrets.STACKHERO_POSTGRESQL_HOST }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DEFAULT_FILE_STORAGE=${{ secrets.DEFAULT_FILE_STORAGE }}

    - name: Run the Docker container
      run: docker run -d -p 8000:8000 --name django_container shaundamon/my-django-app:latest

    - name: Wait for application to start
      run: sleep 10

    - name: Run Tests
      run: docker exec django_container python manage.py test
