name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-django-app

    - name: Run Docker container
      run: docker run -d -p 8000:8000 --name django_container my-django-app

    - name: Check running container
      run: docker ps | grep django_container

    # Add any other steps here if you need to interact with the application
    # For example, to run tests you could execute commands within the container:
    - name: Run Tests
      run: docker exec django_container python manage.py test
